version: '3.8'

services:
  # Node.js application service
  app:
    build: .
    ports:
      - "80:5000" # Expose the Node.js application on port 80
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=finalproject4db
    networks:
      - backend-final
    depends_on:
      - db
      - phpmyadmin
    command: npm start # Adjust the Node.js command
    links:
      - db
    healthcheck:
      # Set up a health check for the Node.js application
      test: [ "CMD-SHELL", "curl -f http://localhost/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend-final:
    driver: bridge
