# main.yaml
name: Build, Test, and Update Data

on:
  push:
    branches: ['main']

jobs:
  update_deployment:
    name: Update Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: npm install -g render-cli

      - name: Login to Render
        run: render login

      - name: Update Render Deployment
        id: update
        run: |
          render update <DEPLOYMENT_ID> \
            --image atillah0/backend-final-4-app:latest \
            --env-file .env
        env:
          DEPLOYMENT_ID: ${{ secrets.RENDER_DEPLOYMENT_ID }}
