# main.yaml
name: Build and publish Docker image

on:
  push:
    branches: ['main']

jobs:
  test:
    name: Run Jest Tests and Update Data
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.dependencies.yaml -f docker-compose.app.yaml up -d

      - name: Run Jest Tests
        run: |
          docker-compose -f docker-compose.dependencies.yaml -f docker-compose.app.yaml run --rm app npm test

      - name: Restart Application
        run: docker-compose -f docker-compose.dependencies.yaml -f docker-compose.app.yaml restart app

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.dependencies.yaml -f docker-compose.app.yaml down

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: atallah0/backend-final-4-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
