# main.yaml
name: Build, Test, and Update Data

on:
  push:
    branches: ['main']

jobs:
  render_auto_update:
    name: Auto-update Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
  
      - name: Install Render CLI
        run: |
          curl -o render https://render.com/static/render-cli-linux
          chmod +x render
          sudo mv render /usr/local/bin/
  
      - name: Configure Render CLI
        run: render configure --api-key ${{ secrets.RENDER_TOKEN }}
  
      - name: Deploy to Render
        run: render deploy --image atallah0/backend-final-4-app:latest
