# main.yaml
name: Build, Test, and Update Data

on:
  push:
    branches: ['main']

jobs:
  update_deployment:
    name: Update Render Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -o render https://render.com/static/render-cli-linux
          chmod +x render
          sudo mv render /usr/local/bin/

      - name: Deploy to Render
        run: |
          render deploy --image atallah0/backend-final-4-app:${{ steps.meta.outputs.tags }} --config docker-compose.app.yaml
