# main.yaml
name: Build, Test, and Update Data

on:
  push:
    branches: ['main']

jobs:
 
  deploy_to_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
  
      - name: Install Render CLI
        run: npm run install-render-cli
  
      - name: Deploy to Render
        run: |
          npx render login --account-token ${{ secrets.RENDER_TOKEN }}
          npx render deploy --image atallah0/backend-final-4-app:${{ steps.meta.outputs.tags }} --config docker-compose.app.yaml

