# main.yaml
name: Build, Test, and Update Data

on:
  push:
    branches: ['main']

jobs:
  deploy_to_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
  
      - name: Install Render CLI
        run: npm install -g render-cli
  
      - name: Deploy to Render
        run: |
          render login --api-key ${{ secrets.RENDER_TOKEN }}
          render deploy --image atallah0/backend-final-4-app:${{ steps.meta.outputs.tags }} --config docker-compose.app.yaml
